### PR TITLE
IPL-903 TakeNote :: Sync Theme With Browser

### PR DESCRIPTION
**Pull request by kamiyargit**
IPL-903 TakeNote :: Sync Theme With Browser

### CODE REVIEW

**Review by amin10043 — APPROVED** [review]

**Review by ghost — APPROVED** [review]
Review submitted

**Review by amin10043 — APPROVED** [review]
Review submitted

**Review by ghost — APPROVED** [review]
Review submitted

**Review by amin10043 — APPROVED** [review]
Review submitted

**Review by ghost — APPROVED** [review]
Review submitted

**Pull request merged**
